"""init

Revision ID: 1c0a8327163e
Revises: 
Create Date: 2018-04-01 13:06:08.183495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0a8327163e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cur_session', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=True)
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.Integer(), nullable=True),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('bat_v', sa.REAL(), nullable=True),
    sa.Column('temp_f', sa.REAL(), nullable=True),
    sa.Column('light_vis', sa.REAL(), nullable=True),
    sa.Column('light_ir', sa.REAL(), nullable=True),
    sa.Column('light_uv', sa.REAL(), nullable=True),
    sa.Column('accel_x', sa.REAL(), nullable=True),
    sa.Column('accel_y', sa.REAL(), nullable=True),
    sa.Column('accel_z', sa.REAL(), nullable=True),
    sa.Column('tilt', sa.REAL(), nullable=True),
    sa.Column('wifi_conn_fail', sa.Integer(), nullable=True),
    sa.Column('mqtt_conn_fail', sa.Integer(), nullable=True),
    sa.Column('last_run_time', sa.REAL(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_timestamp'), 'log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
